<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Subscription extends \App\Entity\Subscription implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Subscription' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Subscription' . "\0" . 'plan', '' . "\0" . 'App\\Entity\\Subscription' . "\0" . 'valid_to', '' . "\0" . 'App\\Entity\\Subscription' . "\0" . 'payment_status', '' . "\0" . 'App\\Entity\\Subscription' . "\0" . 'free_plan_used'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Subscription' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Subscription' . "\0" . 'plan', '' . "\0" . 'App\\Entity\\Subscription' . "\0" . 'valid_to', '' . "\0" . 'App\\Entity\\Subscription' . "\0" . 'payment_status', '' . "\0" . 'App\\Entity\\Subscription' . "\0" . 'free_plan_used'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Subscription $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlan(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlan', []);

        return parent::getPlan();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlan(string $plan): \App\Entity\Subscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlan', [$plan]);

        return parent::setPlan($plan);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidTo(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidTo', []);

        return parent::getValidTo();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidTo(\DateTimeInterface $valid_to): \App\Entity\Subscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidTo', [$valid_to]);

        return parent::setValidTo($valid_to);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentStatus(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentStatus', []);

        return parent::getPaymentStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentStatus(?string $payment_status): \App\Entity\Subscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentStatus', [$payment_status]);

        return parent::setPaymentStatus($payment_status);
    }

    /**
     * {@inheritDoc}
     */
    public function getFreePlanUsed(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFreePlanUsed', []);

        return parent::getFreePlanUsed();
    }

    /**
     * {@inheritDoc}
     */
    public function setFreePlanUsed(bool $free_plan_used): \App\Entity\Subscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFreePlanUsed', [$free_plan_used]);

        return parent::setFreePlanUsed($free_plan_used);
    }

}
