<?php

namespace ContainerNocGqfa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DuY8tN8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DuY8tN8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DuY8tN8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fileUploader' => ['privates', 'App\\Utils\\LocalUploader', 'getLocalUploaderService', true],
        ], [
            'fileUploader' => 'App\\Utils\\LocalUploader',
        ]);
    }
}
