<?php

namespace ContainerNocGqfa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z6NwmtfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z6Nwmtf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z6Nwmtf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\AdminController::index' => ['privates', '.service_locator.MrT.xrC', 'get_ServiceLocator_MrT_XrCService', true],
            'App\\Controller\\Admin\\AdminController::videos' => ['privates', '.service_locator.0XdlIh3', 'get_ServiceLocator_0XdlIh3Service', true],
            'App\\Controller\\Admin\\Superadmin\\CategoryController::categories' => ['privates', '.service_locator.jT4SQLC', 'get_ServiceLocator_JT4SQLCService', true],
            'App\\Controller\\Admin\\Superadmin\\CategoryController::getAllCategories' => ['privates', '.service_locator.0XdlIh3', 'get_ServiceLocator_0XdlIh3Service', true],
            'App\\Controller\\Admin\\Superadmin\\SuperAdminController::deleteVideo' => ['privates', '.service_locator.DuY8tN8', 'get_ServiceLocator_DuY8tN8Service', true],
            'App\\Controller\\Admin\\Superadmin\\SuperAdminController::videosUpload' => ['privates', '.service_locator.DuY8tN8', 'get_ServiceLocator_DuY8tN8Service', true],
            'App\\Controller\\FrontController::deleteComment' => ['privates', '.service_locator.Vc6vB.a', 'get_ServiceLocator_Vc6vB_AService', true],
            'App\\Controller\\FrontController::index' => ['privates', '.service_locator.q1dUsQv', 'get_ServiceLocator_Q1dUsQvService', true],
            'App\\Controller\\FrontController::searchResults' => ['privates', '.service_locator.q1dUsQv', 'get_ServiceLocator_Q1dUsQvService', true],
            'App\\Controller\\FrontController::videoList' => ['privates', '.service_locator.WsrPTid', 'get_ServiceLocator_WsrPTidService', true],
            'App\\Controller\\FrontController::video_details' => ['privates', '.service_locator.UocBbJu', 'get_ServiceLocator_UocBbJuService', true],
            'App\\Controller\\PaypalController::PaypalVerify' => ['privates', '.service_locator.Ew5DOJh', 'get_ServiceLocator_Ew5DOJhService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.RuRUNGK', 'get_ServiceLocator_RuRUNGKService', true],
            'App\\Controller\\SubscriptionController::payment' => ['privates', '.service_locator.aI7umW_', 'get_ServiceLocator_AI7umWService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\Admin\\AdminController:index' => ['privates', '.service_locator.MrT.xrC', 'get_ServiceLocator_MrT_XrCService', true],
            'App\\Controller\\Admin\\AdminController:videos' => ['privates', '.service_locator.0XdlIh3', 'get_ServiceLocator_0XdlIh3Service', true],
            'App\\Controller\\Admin\\Superadmin\\CategoryController:categories' => ['privates', '.service_locator.jT4SQLC', 'get_ServiceLocator_JT4SQLCService', true],
            'App\\Controller\\Admin\\Superadmin\\CategoryController:getAllCategories' => ['privates', '.service_locator.0XdlIh3', 'get_ServiceLocator_0XdlIh3Service', true],
            'App\\Controller\\Admin\\Superadmin\\SuperAdminController:deleteVideo' => ['privates', '.service_locator.DuY8tN8', 'get_ServiceLocator_DuY8tN8Service', true],
            'App\\Controller\\Admin\\Superadmin\\SuperAdminController:videosUpload' => ['privates', '.service_locator.DuY8tN8', 'get_ServiceLocator_DuY8tN8Service', true],
            'App\\Controller\\FrontController:deleteComment' => ['privates', '.service_locator.Vc6vB.a', 'get_ServiceLocator_Vc6vB_AService', true],
            'App\\Controller\\FrontController:index' => ['privates', '.service_locator.q1dUsQv', 'get_ServiceLocator_Q1dUsQvService', true],
            'App\\Controller\\FrontController:searchResults' => ['privates', '.service_locator.q1dUsQv', 'get_ServiceLocator_Q1dUsQvService', true],
            'App\\Controller\\FrontController:videoList' => ['privates', '.service_locator.WsrPTid', 'get_ServiceLocator_WsrPTidService', true],
            'App\\Controller\\FrontController:video_details' => ['privates', '.service_locator.UocBbJu', 'get_ServiceLocator_UocBbJuService', true],
            'App\\Controller\\PaypalController:PaypalVerify' => ['privates', '.service_locator.Ew5DOJh', 'get_ServiceLocator_Ew5DOJhService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.RuRUNGK', 'get_ServiceLocator_RuRUNGKService', true],
            'App\\Controller\\SubscriptionController:payment' => ['privates', '.service_locator.aI7umW_', 'get_ServiceLocator_AI7umWService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\Admin\\AdminController::index' => '?',
            'App\\Controller\\Admin\\AdminController::videos' => '?',
            'App\\Controller\\Admin\\Superadmin\\CategoryController::categories' => '?',
            'App\\Controller\\Admin\\Superadmin\\CategoryController::getAllCategories' => '?',
            'App\\Controller\\Admin\\Superadmin\\SuperAdminController::deleteVideo' => '?',
            'App\\Controller\\Admin\\Superadmin\\SuperAdminController::videosUpload' => '?',
            'App\\Controller\\FrontController::deleteComment' => '?',
            'App\\Controller\\FrontController::index' => '?',
            'App\\Controller\\FrontController::searchResults' => '?',
            'App\\Controller\\FrontController::videoList' => '?',
            'App\\Controller\\FrontController::video_details' => '?',
            'App\\Controller\\PaypalController::PaypalVerify' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::register' => '?',
            'App\\Controller\\SubscriptionController::payment' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\AdminController:index' => '?',
            'App\\Controller\\Admin\\AdminController:videos' => '?',
            'App\\Controller\\Admin\\Superadmin\\CategoryController:categories' => '?',
            'App\\Controller\\Admin\\Superadmin\\CategoryController:getAllCategories' => '?',
            'App\\Controller\\Admin\\Superadmin\\SuperAdminController:deleteVideo' => '?',
            'App\\Controller\\Admin\\Superadmin\\SuperAdminController:videosUpload' => '?',
            'App\\Controller\\FrontController:deleteComment' => '?',
            'App\\Controller\\FrontController:index' => '?',
            'App\\Controller\\FrontController:searchResults' => '?',
            'App\\Controller\\FrontController:videoList' => '?',
            'App\\Controller\\FrontController:video_details' => '?',
            'App\\Controller\\PaypalController:PaypalVerify' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:register' => '?',
            'App\\Controller\\SubscriptionController:payment' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
