<?php

namespace ContainerNocGqfa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocalUploaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Utils\LocalUploader' shared autowired service.
     *
     * @return \App\Utils\LocalUploader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Utils/LocalUploader.php';

        return $container->privates['App\\Utils\\LocalUploader'] = new \App\Utils\LocalUploader((\dirname(__DIR__, 4).'/public/uploads/videos'));
    }
}
