<?php

namespace ContainerXxkWTsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WsrPTidService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WsrPTid' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WsrPTid'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cache' => ['privates', 'App\\Utils\\FilesCache', 'getFilesCacheService', false],
            'categories' => ['privates', 'App\\Utils\\CategoryTreeFrontPage', 'getCategoryTreeFrontPageService', true],
            'video_no_members' => ['privates', 'App\\Utils\\VideoForNotValidSubscription', 'getVideoForNotValidSubscriptionService', true],
        ], [
            'cache' => '?',
            'categories' => 'App\\Utils\\CategoryTreeFrontPage',
            'video_no_members' => 'App\\Utils\\VideoForNotValidSubscription',
        ]);
    }
}
