<?php

namespace ContainerXxkWTsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0XdlIh3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0XdlIh3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0XdlIh3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categories' => ['privates', 'App\\Utils\\CategoryTreeAdminOptionList', 'getCategoryTreeAdminOptionListService', true],
        ], [
            'categories' => 'App\\Utils\\CategoryTreeAdminOptionList',
        ]);
    }
}
