<?php

namespace ContainerXxkWTsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ew5DOJhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ew5DOJh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ew5DOJh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paypalIPN' => ['privates', 'App\\Utils\\PaypalIPN', 'getPaypalIPNService', true],
        ], [
            'paypalIPN' => 'App\\Utils\\PaypalIPN',
        ]);
    }
}
