<?php

namespace ContainerXxkWTsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q1dUsQvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q1dUsQv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q1dUsQv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'video_no_members' => ['privates', 'App\\Utils\\VideoForNotValidSubscription', 'getVideoForNotValidSubscriptionService', true],
        ], [
            'video_no_members' => 'App\\Utils\\VideoForNotValidSubscription',
        ]);
    }
}
