<?php

namespace ContainerXxkWTsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaypalIPNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Utils\PaypalIPN' shared autowired service.
     *
     * @return \App\Utils\PaypalIPN
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Utils/PaypalIPN.php';

        return $container->privates['App\\Utils\\PaypalIPN'] = new \App\Utils\PaypalIPN();
    }
}
