<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxkWTsx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxkWTsx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxkWTsx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxkWTsx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxkWTsx\App_KernelDevDebugContainer([
    'container.build_hash' => 'XxkWTsx',
    'container.build_id' => 'c746b319',
    'container.build_time' => 1594738150,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxkWTsx');
